language: swift
osx_image: xcode11.3
xcode_project: Prelude.xcodeproj

matrix:
  include:
    - xcode_scheme: Prelude-Package
      xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 11
    - xcode_scheme: Prelude-Package
      xcode_destination: platform=OS X,arch=x86_64
