name: Run Tests
on: push

jobs:
  test-macOS:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: xcodebuild
        run: xcodebuild -project Prelude.xcodeproj -scheme "Prelude-Package" -destination "platform=OS X,arch=x86_64" build test | xcpretty
      - name: SwiftPM Build
        run: swift build
  test-iOS:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: xcodebuild
        run: xcodebuild -project Prelude.xcodeproj -scheme "Prelude-Package" -destination "platform=iOS Simulator,OS=13.3,name=iPhone 11" build test | xcpretty
  test-linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.1.3
    steps:
      - uses: actions/checkout@v1.0.0
      - name: SwiftPM Build
        run: swift test
