name: Run Tests
on: push

jobs:
  test-macOS:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: xcodebuild
        run: xcodebuild -project Prelude.xcodeproj -scheme "Prelude macOS" -destination "platform=OS X,arch=x86_64" build test | xcpretty
      - name: SwiftPM Build
        run: swift build
  test-iOS:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: xcodebuild
        run: xcodebuild -project Prelude.xcodeproj -scheme "Prelude iOS" -destination "platform=iOS Simulator,OS=13.1,name=iPhone 11" build test | xcpretty
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: SwiftPM Build
        run: swift test
        uses: docker://swift:5.1
